In [4]:
from __future__ import print_function
import torch
x = torch.empty(5, 3)
print (x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.1873, 0.8824, 0.0573],
        [0.8094, 0.5336, 0.0626],
        [0.3517, 0.8502, 0.3400],
        [0.2744, 0.5460, 0.6267],
        [0.2764, 0.7761, 0.1853]])


In [8]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8050, -0.8977, -0.0350],
        [ 0.4639, -0.9146, -0.5042],
        [-0.1290,  0.8035,  0.3429],
        [ 0.1680, -0.7418, -0.8753],
        [-0.0123,  0.5097,  1.1642]])


In [14]:
print(x.size)

<built-in method size of Tensor object at 0x11ecc6030>


In [16]:
print(x.size())

torch.Size([5, 3])


In [18]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.8108, -0.1122,  0.9393],
        [ 0.7147, -0.7297,  0.1300],
        [-0.0759,  1.5345,  1.0935],
        [ 1.0334,  0.0368, -0.4277],
        [ 0.1105,  1.4172,  2.0546]])


In [20]:
print(torch.add(x, y))

tensor([[ 0.8108, -0.1122,  0.9393],
        [ 0.7147, -0.7297,  0.1300],
        [-0.0759,  1.5345,  1.0935],
        [ 1.0334,  0.0368, -0.4277],
        [ 0.1105,  1.4172,  2.0546]])


In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.8108, -0.1122,  0.9393],
        [ 0.7147, -0.7297,  0.1300],
        [-0.0759,  1.5345,  1.0935],
        [ 1.0334,  0.0368, -0.4277],
        [ 0.1105,  1.4172,  2.0546]])


In [24]:
y.add_(x)
print (y)

tensor([[ 0.8108, -0.1122,  0.9393],
        [ 0.7147, -0.7297,  0.1300],
        [-0.0759,  1.5345,  1.0935],
        [ 1.0334,  0.0368, -0.4277],
        [ 0.1105,  1.4172,  2.0546]])


In [26]:
print(x[:, 1])

tensor([-0.8977, -0.9146,  0.8035, -0.7418,  0.5097])


In [28]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [30]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6369])
-0.6368641257286072


In [32]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [38]:
a.add_(1)
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [46]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
